---
title: "Working with Data"
output: html_document
---

```{r}
library(readr)
library(maps)
```

# Read Data
```{r}
# Create bakeoff from "bakeoff.csv"
bakeoff <- read_csv("bakeoff.csv")
summary(bakeoff)
# Print bakeoff
print(bakeoff)
```

# Summary
```{r}
# Load dplyr
library(dplyr)
```

```{r}
#Glimpse
str(bakeoff)
bakeoff%>%glimpse()
```

# QUIZZ ALERTA
```{r}
# Take a glimpse of the bakeoff data we imported in the first set of exercises. 
#On which date did the first episode of the show air in the US?
```



```{r}
bakeoff %>% 
  filter(!is.na(us_airdate)) %>%
  glimpse() # no argument needed here
```


# Skim

```{r}
bakeoff %>% skim()
```

```{r}
# Load skimr
library(skimr)

# Filter and skim
bakeoff %>% 
  filter(!is.na(us_season)) %>% 
  skim()
```




```{r}
# Edit to filter, group by, and skim
bakeoff %>% 
  filter(!is.na(us_season)) %>% 
  group_by(us_season) %>% 
  skim()
```


```{r}
# Know our variable type
bakeoff %>% 
  skim() %>%  # no argument needed here
  summary() # no argument needed here
```






# Count with Data
```{r}
bakeoff
```


```{r}
# View distinct results
bakeoff %>% 
  distinct(result)
```

```{r}
# Count rows for each result
bakeoff %>% 
  count(result)
```


```{r}
# Count whether or not star baker
bakeoff %>% 
  count(result == "SB")
```

```{r}
# Count the number of rows by series and episode
bakeoff %>% 
  count(series, episode)
```


```{r}
# Count the number of rows by series and baker
bakers_by_series <- bakeoff %>% 
  count(series, baker)
  
# Print to view
bakers_by_series
```


```{r}
# Count again by series
bakers_by_series %>% 
  count(series)
```

```{r}
# Unsorted count
bakers_by_series %>%
  count(baker)
```


```{r}
# Count again by baker
bakers_by_series %>%
  count(baker, sort = TRUE)
```











# Tame our Data
```{r}
# Find format to parse "17 August 2010" 
parse_date("17 August 2010", format = "%d %B %Y")
```

```{r}
(desserts <- read_csv("desserts.csv"))
```

```{r}
# Arrange by descending uk_airdate????
desserts %>% 
    arrange(desc(uk_airdate))
```








```{r}
# Edit to cast uk_airdate
desserts <- read_csv("desserts.csv", 
                     col_types = cols(
                       uk_airdate = col_date(format = "%d %B %Y")))
desserts
```


```{r}
# Arrange by descending uk_airdate
desserts %>% 
    arrange(desc(uk_airdate))
```

```{r}
(desserts <- read_csv("desserts.csv"))
```


```{r}
# Try to cast technical as a number
desserts <- read_csv("desserts.csv", 
                     col_types = cols(
           			   uk_airdate = col_date(format = "%d %B %Y"),
                       technical = col_number()))
desserts
```

```{r}
# View parsing problems
problems(desserts)
```


```{r}
# Edit code to fix the parsing error 
desserts <- read_csv("desserts.csv",
                      col_types = cols(
                        uk_airdate = col_date(format = "%d %B %Y"),
                        technical = col_number()), na = c("", "NA", "N/A"))
desserts
# View parsing problems
problems(desserts)
```


```{r}
# Cast result a factor
desserts <- read_csv("desserts.csv", 
                     na = c("", "NA", "N/A"),
                     col_types = cols(
                       uk_airdate = col_date(format = "%d %B %Y"),
                       technical = col_number(),                       
                       result = col_factor(levels = NULL)
                     )
                    )

# Glimpse to view
glimpse(desserts)
```







# Recode Value

## Recode a character variable
```{r}
# Count rows grouping by nut variable
desserts %>% 
    count(signature_nut, sort = TRUE)
```

```{r}
# Recode filberts as hazelnuts
desserts_2 <- desserts %>% 
  mutate(signature_nut = recode(signature_nut, "filbert" = "hazelnut"))
desserts_2

# Count rows again
desserts_2 %>% 
    count(signature_nut, sort = TRUE)
```

```{r}
# Edit code to recode "no nut" as missing
desserts_2 <- desserts %>% 
  mutate(signature_nut = recode(signature_nut, "filbert" = "hazelnut", 
                           "no nut" = NA_character_))

# Count rows again
desserts_2 %>% 
    count(signature_nut, sort = TRUE)
```


# Recode a numeric variable
```{r}
# Create dummy variable: 1 if won, 0 if not
desserts <- desserts %>% 
  mutate(tech_win = recode(technical, `1` = 1,
                           .default = 0))
desserts%>%count()
```


```{r}
# Count to compare values                      
desserts %>% 
  count(technical == 1, tech_win)
```

```{r}
# Edit to recode tech_win as factor
desserts <- desserts %>% 
  mutate(tech_win = recode_factor(technical, `1` = 1,
                                  .default = 0))

# Count to compare values                      
desserts %>% 
  count(technical == 1, tech_win)
```




# Select data
```{r}
ratings <- read_csv("02.03_messy_ratings.csv")
ratings
```

```{r}
# Recode channel as factor: "Channel 4" (0) or not (1)
ratings <- ratings %>% 
  mutate(bbc = recode_factor(channel, 
                             "Channel 4" = 0,
                             .default = 1))
ratings
```

```{r}
# Select to look at variables to plot next
ratings %>% 
  select(series, channel, bbc)
```

```{r}
library(ggplot2)
```


```{r}
# Make a filled bar chart
ggplot(ratings, aes(x = series, y = e5_viewers_7day, fill = bbc)) +geom_col()
```


```{r}
# Move channel to first column
ratings %>% 
  select(channel, everything())
```

```{r}
# Drop 7- and 28-day episode ratings
ratings %>% 
  select(-ends_with("day"))
```

```{r}
# Move channel to front and drop 7-/28-day episode ratings
ratings %>% 
  select(channel, everything(), -ends_with("day"))
```


```{r}
# Glimpse to see variable names
messy_ratings <- read.csv("messy_ratings.csv")
glimpse(messy_ratings)

# Load janitor
install.packages("janitor")
library(janitor)
```

```{r}
# Select 7-day viewer data by series
library(dplyr)
viewers_7day <- ratings%>%select(series,ends_with("7day"))
ratings
# Glimpse
glimpse(viewers_7day)
```

```{r}
# Adapt code to also rename 7-day viewer data
viewers_7day <- ratings %>% 
    select(series, viewers_7day_ = ends_with("7day"))

# Glimpse
glimpse(viewers_7day)
```

```{r}
# Adapt code to drop 28-day columns; keep 7-day in front
viewers_7day <- ratings %>% 
    select(viewers_7day_ = ends_with("7day"), 
           everything(), 
           -ends_with("28day"))

# Glimpse
glimpse(viewers_7day)
```


```{r}
# Adapt code to keep original order
viewers_7day <- ratings %>% 
    select(everything(), 
           viewers_7day_ = ends_with("7day"), 
           -ends_with("28day"))

# Glimpse
glimpse(viewers_7day)
```



# TIDY DATA
```{r}
library(readr)
ratings <- read_csv("messy_ratings.csv")
ratings
```

## Plot UNTIDY
```{r}
# Plot of episode 1 viewers by series
library(ggplot2)
ggplot(ratings, aes(x = series, y = e1)) +
    geom_col()
```

```{r}
# Adapt code to plot episode 2 viewers by series
ggplot(ratings, aes(x = series, y = e2)) +
    geom_col()
```

```{r}
ratings
```


```{r}
library(tidyverse)

tidy_ratings <- ratings %>%
    # Gather and convert episode to factor
	gather(key = "episode", value = "viewers_7day", -series, 
           factor_key = TRUE, na.rm = TRUE)
tidy_ratings
```

```{r}
tidy_ratings <- ratings %>%
	# Gather and convert episode to factor
    gather(key = "episode", value = "viewers_7day", -series, 
           factor_key = TRUE, na.rm = TRUE) %>% 
	# Sort in ascending order by series and episode
    arrange(series, episode)
tidy_ratings
```

```{r}
tidy_ratings <- ratings %>%
	# Gather and convert episode to factor
    gather(key = "episode", value = "viewers_7day", -series, 
           factor_key = TRUE, na.rm = TRUE) %>% 
	# Sort in ascending order by series and episode
    arrange(series, episode) %>%
	# Create new variable using row_number()
    mutate(episode_count = row_number())
tidy_ratings
```

```{r}
# Plot viewers by episode and series
ggplot(tidy_ratings, aes(x = episode_count, 
                         y = viewers_7day, 
                         fill = as.factor(series))) +
    geom_col()
```

